spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopmall?serverTimezone=UTC
    username: root
    password: ",=6_t2G:i5(h"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  resources:
    static-locations: classpath:static/
  mvc:
    static-path-pattern: /static/**
server:
  port: 8081
  servlet:
    context-path: /shopmall